SELECT DNAME,LOC FROM DEPT;
SELECT EMPNO,ENAME FROM EMP;
SELECT ENAME,SAL,JOB,COMM FROM EMP;
SELECT SAL,(SAL*12) AS 'ANUAL SALARY' FROM EMP;
SELECT DISTINCT DEPTNO FROM DEPT;
SELECT ((SAL*20/100)+SAL)*12 AS 'ANUAL SALARY' FROM EMP; 
