SELECT E.EMPNO,E.ENAME,J.STARTDATE,J.ENDDATE,J.CHGDESC
FROM EMP E
FULL OUTER JOIN
JOBHIST J
ON(E.EMPNO=J.EMPNO)
WHERE E.EMPNO IN (SELECT EMPNO
				FROM EMP
				UNION
				SELECT EMPNO
				FROM JOBHIST)
				ORDER BY J.STARTDATE DESC;


SELECT EMPNO,JOB
FROM EMP
WHERE JOB='SALESMAN'
INTERSECT
SELECT EMPNO,JOB
FROM JOBHIST
WHERE JOB='SALESMAN';

SELECT E.EMPNO,E.ENAME,D.DEPTNO,D.DNAME
FROM DEPT D
FULL OUTER JOIN
EMP E
ON(D.DEPTNO=E.DEPTNO)
WHERE D.DEPTNO IN (SELECT D.DEPTNO
				FROM DEPT D
				UNION
				SELECT D.DEPTNO
				FROM EMP E);
				
