SELECT * FROM Bonus;
SELECT * FROM Title;
SELECT * FROM Worker_Details;

SELECT CONCAT(FIRST_NAME,LAST_NAME) AS 'TITLE(CONSULTANT)',DEPARTMENT
FROM WORKER_DETAILS
WHERE WORKER_ID IN(SELECT WORKER_REF_ID FROM TITLE WHERE WORKER_TITLE='CONSULTANT');

SELECT DEPARTMENT,
MAX(SALARY) AS 'MAXIMUM_SALARY'
FROM WORKER_DETAILS
GROUP BY DEPARTMENT;