SELECT ENAME,JOB FROM EMP
WHERE JOB='CLERK';

SELECT ENAME,SAL FROM EMP
WHERE SAL BETWEEN 500 AND 1000;

SELECT ENAME,SAL FROM EMP
WHERE SAL NOT BETWEEN 1000 AND 2500;

SELECT ENAME,SAL FROM EMP
WHERE SAL IN(800,950,3000,5000);

SELECT ENAME FROM EMP
WHERE ENAME LIKE '_L%';

SELECT ENAME FROM EMP
WHERE ENAME LIKE '%D';

SELECT ENAME FROM EMP
WHERE ENAME LIKE '_____';

SELECT ENAME FROM EMP
WHERE ENAME LIKE 'T%R';

SELECT ENAME FROM EMP
WHERE ENAME LIKE '%A%';






