select e.ename,E.EMPNO,d.loc
from emp e JOIN dept d 
ON (E.DEPTNO=D.DEPTNO) AND D.LOC='CHICAGO';

select e.ename,E.EMPNO,d.loc,D.DEPTNO 
from emp e JOIN dept d 
ON (E.DEPTNO=D.DEPTNO)
ORDER BY LOC;

select e.ename AS MANAGER , c.ename AS EMPLOYEE
from emp C JOIN emp E
ON (e.empno = c.mgr) and e.HIREDATE > c.HIREDATE;

SELECT E.ENAME, D.DNAME 
FROM EMP E JOIN DEPT D
ON (E.DEPTNO=D.DEPTNO)

SELECT  E.ENAME,E.EMPNO,D.LOC,D.DEPTNO
FROM EMP E JOIN DEPT D
ON (E.DEPTNO=D.DEPTNO);

SELECT E.EMPNO,E.ENAME,E.HIREDATE,J.STARTDATE,J.ENDDATE
FROM EMP E JOIN JOBHIST J
ON E.HIREDATE BETWEEN J.STARTDATE AND J.ENDDATE;
