CREATE TABLE PET_DETAILS
(PET_ID             int NOT NULL,
 PETNAME              VARCHAR(14),
 PETTYPE                VARCHAR(13),
 PETAGE                VARCHAR(13),
 PETOWNER                VARCHAR(13),
 CONSTRAINT PET_ID_PRIMARY_KEY PRIMARY KEY (PET_ID));


CREATE TABLE TREATMENT
(PET_ID             int NOT NULL,
VISITDATE          DATE,
PROCEDURESS          VARCHAR(13),
CONSTRAINT PET_ID_FOREIGN_KEY FOREIGN KEY (PET_ID) REFERENCES PET_DETAILS (PET_ID));

CREATE TABLE OWNER
(PET_ID             int NOT NULL,
PETOWNER             VARCHAR(20),
PROCEDURESS          VARCHAR(13),
CONSTRAINT PETID_FOREIGN_KEY FOREIGN KEY (PET_ID) REFERENCES PET_DETAILS (PET_ID));

INSERT INTO PET_DETAILS VALUES (246,'ROVER','DOG',12,'SAM COOK');
INSERT INTO PET_DETAILS VALUES (298,'SPOT','DOG',2,'TERRY KIM');
INSERT INTO PET_DETAILS VALUES (341,'MORRIS','CAT',4,'SAM COOK');
INSERT INTO PET_DETAILS VALUES (519,'TWEEDY','BIRD',2,'TERRY KIM');

ALTER TABLE TREATMENT 
ALTER COLUMN PROCEDURESS VARCHAR(200);

INSERT INTO TREATMENT VALUES (246,'13-JAN-2002','01-RABIES VACCINATION');
INSERT INTO TREATMENT VALUES (298,'1-MAR-2002','08-HEART WARM VACCINATION');
INSERT INTO TREATMENT VALUES (341,'23-JAN-2001','01-RABIES VACCINATION');
INSERT INTO TREATMENT VALUES (519,'1-MAR-2002','20-EYE VACCINATION');

INSERT INTO OWNER VALUES (246,'SAM COOK');
INSERT INTO OWNER VALUES (298,'TERRY KIM');
INSERT INTO OWNER VALUES (341,'SAM COOK');
INSERT INTO OWNER VALUES (519,'TERRY KIM');

